
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('rafael', 'talavera','rtalavera@live.com.ar', '2021-02-15')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Juan', 'Pérez', 'juan.perez@example.com', '2021-02-15')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Ana', 'González', 'ana.gonzalez@example.com', '2021-03-20')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Luis', 'Rodríguez', 'luis.rodriguez@example.com', '2021-04-25')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('María', 'López', 'maria.lopez@example.com', '2021-05-30')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Carlos', 'Martínez', 'carlos.martinez@example.com', '2021-06-05')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Sofía', 'Fernández', 'sofia.fernandez@example.com', '2021-07-10')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Pedro', 'Ramírez', 'pedro.ramirez@example.com', '2021-08-15')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Laura', 'Torres', 'laura.torres@example.com', '2021-09-20')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Miguel', 'Gómez', 'miguel.gomez@example.com', '2021-10-25')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Carmen', 'Díaz', 'carmen.diaz@example.com', '2021-11-30')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Diego', 'Hernández', 'diego.hernandez@example.com', '2022-01-05')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Raquel', 'Sánchez', 'raquel.sanchez@example.com', '2022-02-10')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Andrés', 'Pérez', 'andres.perez@example.com', '2022-03-15')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Isabel', 'González', 'isabel.gonzalez@example.com', '2022-04-20')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Javier', 'López', 'javier.lopez@example.com', '2022-05-25')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Elena', 'Martínez', 'elena.martinez@example.com', '2022-06-30')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('José', 'Fernández', 'jose.fernandez@example.com', '2022-07-05')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Beatriz', 'Ramírez', 'beatriz.ramirez@example.com', '2022-08-10')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Antonio', 'Torres', 'antonio.torres@example.com', '2022-09-15')
 INSERT INTO clientes (nombre, apellido, email, fecha) VALUES('Lucía', 'Gómez', 'lucia.gomez@example.com', '2022-10-20')
  